### ISSUE TITLE
Read The Docs Won't Build

### ISSUE THREAD

**Issue by kb1lqc** [FaradayRF/faradayio#12]
I am trying to build the documentation with `sphinx` using Read The Docs located at https://readthedocs.org/projects/faradayio/. However, there is no automatically generated module documentation. Locally, sphinx builds this fine. Investigating Read The Docs output shows that the `sliplib` import fails (it's manually built with a git clone, not pip install due to too old pypi version).

I believe this should work once @rhjdjong updates PyPi with a newer version and I can simply include sliplib in the `requirements.txt` file.

```
Running Sphinx v1.6.5
making output directory...
loading translations [en]... done
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [readthedocs]: targets for 2 source files that are out of date
updating environment: 0 added, 1 changed, 0 removed
reading sources... [100%] code

/home/docs/checkouts/readthedocs.org/user_builds/faradayio/checkouts/master/docs/code.rst:4: WARNING: autodoc: failed to import module 'faradayio.faraday'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/faradayio/envs/master/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/faradayio/checkouts/master/faradayio/faraday.py", line 10, in <module>
    import sliplib
ImportError: No module named 'sliplib'
/home/docs/checkouts/readthedocs.org/user_builds/faradayio/checkouts/master/docs/code.rst:8: WARNING: autodoc: failed to import class 'Faraday' from module 'faradayio.faraday'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/faradayio/envs/master/lib/python3.5/site-packages/sphinx/ext/autodoc.py", line 658, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/faradayio/checkouts/master/faradayio/faraday.py", line 10, in <module>
    import sliplib
ImportError: No module named 'sliplib'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /home/docs/checkouts/readthedocs.org/user_builds/faradayio/checkouts/master/docs/code.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [ 50%] code
writing output... [100%] index

generating indices... genindex
writing additional pages... search
copying static files... WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/user_builds/faradayio/checkouts/master/docs/_static' does not exist
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/readthedocs/templates/sphinx/_static' does not exist
done
copying readthedocs static files... done
copying searchtools... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 5 warnings.
```

Locally built HTML documentation shows `sphinx` is working fine:
![image](https://user-images.githubusercontent.com/331540/34321143-1762d22a-e7bd-11e7-890b-12e6aec741ce.png)

![image](https://user-images.githubusercontent.com/331540/34321146-264ac0cc-e7bd-11e7-955c-58d3abce2bdc.png)

**Comment by rhjdjong** [comment]
Hi, I don't know if this issue is still relevant. But I would like to let you know that SlipLib has in the meantime been updated a few times, and is nearing release 1.0. I expect that the RTD builds should be successful now.
Cheers, Ruud

**Comment by kb1lqc** [comment]
Thanks!
